<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RepositoryUrl>https://github.com/ruifrvaz/Daisy-m4</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Daisy.Resources\Daisy.Resources.csproj" />
    <ProjectReference Include="..\Daisy.Factories\Daisy.Factories.csproj" />
    
    <!-- Plugin Projects - Direct References Using Wildcards -->
    <!-- Abilities -->
    <ProjectReference Include="..\Daisy.Abilities\*\*.csproj" />
    
    <!-- Receivers -->
    <ProjectReference Include="..\Daisy.Receivers\*\*.csproj" />
    
    <!-- Transmitters -->
    <ProjectReference Include="..\Daisy.Transmitters\*\*.csproj" />
    
    <!-- Workflows -->
    <ProjectReference Include="..\Daisy.Workflows\*\*.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>